const berserkerBuilds = [
  {
    title: 'Busted Blade',
    subclass: 'Wolf Emblem',
    items: 'Greatsword, Box of Riches',
    gallery: ['berserker1.webp'],
    description: 'Try to use all the pet spaces',
    tier: 'S',
  },
  {
    title: 'Magic Torch + Manathirst',
    subclass: 'Wolf Emblem',
    items: 'Manapotion, Torch',
    gallery: ['berserker2.png', 'berserker2-1.png'],
    description: 'Try to use all the pet spaces',
    tier: 'S',
  },
  {
    title: 'Spike Staff',
    subclass: 'Deerwood',
    items: 'Mana Orb',
    gallery: ['berserker3.webp'],
    description: '',
    tier: 'A',
  },
];

const pyromancerBuilds = [
  {
    title: 'Flame Whip',
    subclass: 'Frozen Flame',
    items: 'Thorn Whip',
    gallery: ['pyromancer1.png'],
    description: 'Buy as many Prismatic Orbs and ice items as you can',
    tier: 'S',
  },
  {
    title: 'Flame Whip',
    subclass: 'Dark Lantern',
    items: 'Thorn Whip',
    gallery: ['pyromancer2.png'],
    description:
      "Buy as many Maneki-neko's, Prismatic Orbs and Glowing Crown's as possible",
    tier: 'A',
  },
  {
    title: 'Lightsaber',
    subclass: 'Burning Banner',
    items: 'Lightsaber, Oil Lamp',
    gallery: ['pyromancer3.webp'],
    description: '',
    tier: 'A',
  },
  {
    title: 'Pandamonium Darksaber',
    subclass: 'Dark Lantern',
    items: 'Pan, Corrupted Crystal, Lightsaber',
    gallery: ['pyromancer4.webp'],
    description:
      "You'll need at least 3 Corrupted Crystal's, if you come early it's a good build",
    tier: 'A',
  },
  {
    title: 'Bloodthorne',
    subclass: 'Burning Banner',
    items: 'Hungry Blade, Thorn Whip',
    gallery: ['pyromancer6.png'],
    description: "Buy as many Maneki-neko's and Prismatic Orbs as possible",
    tier: 'A',
  },
  {
    title: 'Eggscalibur',
    subclass: 'Burning Banner',
    items: 'Pan, Heroic Potion',
    gallery: ['pyromancer7.webp'],
    description: '',
    tier: 'B',
  },
];

const rangerBuilds = [
  {
    title: 'Falcon Blade',
    subclass: 'Piercing Arrow',
    items: 'Whetstone, Gloves of Haste, Oil Lamp',
    gallery: ['ranger1.png'],
    description: "Buff the damage of the Falcon Blade and buy Prismatic Orb's",
    tier: 'S',
  },
  {
    title: 'Hero Longsword',
    subclass: 'Mega Clover',
    items: "Whetstone, Fortuna's Hope",
    gallery: ['ranger2.webp'],
    description: '',
    tier: 'B',
  },
  {
    title: 'Magic Staff',
    subclass: 'Piercing Arrow',
    items: 'Mana Orb, Gloves of Haste',
    gallery: ['ranger3.webp'],
    description: 'Early Mana Orbs',
    tier: 'B',
  },
  {
    title: 'Fancy Fencing Rapier',
    subclass: 'Piercing Arrow',
    items: 'Fancy Fencing Rapier, Mana Orb, Gloves of Haste',
    gallery: ['ranger4.webp'],
    description: 'Early Gloves of Haste and Rapier',
    tier: 'A',
  },
  {
    title: 'Thornbloom + Pets',
    subclass: 'Big Bowl',
    items: 'Thorn Whip, Heroic Potion',
    gallery: ['ranger5.webp'],
    description: '',
    tier: 'A',
  },
  {
    title: 'Hammer + Dagger',
    subclass: 'Mega Clover',
    items: 'Hammer, Dagger, Strong Heroic Potion, Blood Amulet',
    gallery: ['ranger6.webp'],
    description: '',
    tier: 'B',
  },
  {
    title: 'Ranger + Pyromancer Item',
    subclass: 'Yggdrasil Leaf',
    items: 'Pan, Heroic Potion',
    gallery: ['ranger7.png'],
    description: '',
    tier: 'A',
  },
  {
    title: 'Holy Spear',
    subclass: 'Big Bowl',
    items: 'Hero Sword, Goobert, Holy Spear',
    gallery: ['ranger8.png'],
    description: '',
    tier: 'A',
  },
];

const reaperBuilds = [
  {
    title: 'Falcon Blade',
    subclass: 'Nocturnal Lock Lifter',
    items: 'Gloves of Haste, Oil Lamp, Vampiric Items',
    gallery: ['reaper1.png', 'reaper1-1.png'],
    description: 'You need a lot of vampiric items',
    tier: 'S',
  },
  {
    title: 'Chonk Unhealing',
    subclass: 'Mr. Struggles',
    items: 'Mana Orb, Demonic Flask, Deck of Cards, Ruby Egg',
    gallery: ['reaper2.webp'],
    description: '',
    tier: 'A',
  },
  {
    title: 'Magic Torch + Manathirst',
    subclass: 'Nocturnal Lock Lifter',
    items: 'Mana Potion, Mana Orb, Hungry Blade, Deck of Cards, Ruby Egg',
    gallery: ['reaper3.webp'],
    description: '',
    tier: 'A',
  },
  {
    title: 'Eggscalibur + Amulet of Feasting',
    subclass: 'Cauldron',
    items: 'Amulet of Feasting, Pan, Heroic Potion, Cheese',
    gallery: ['reaper5.webp'],
    description: '',
    tier: 'A',
  },
];
